AT_Pedro-Paiva/Models/Amigo.cs
using AT_Pedro_Paiva.DB;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;

namespace AT_Pedro_Paiva.Models
{
    public class Amigo
    {
        public List<AmigoModel> listaAmigos = new List<AmigoModel>();
        public List<AmigoModel> buscaAmigo = new List<AmigoModel>();
        public List<AmigoModel> listaAmigosOrdenados = new List<AmigoModel>();
        public List<AmigoModel> listaAmigosDoDia = new List<AmigoModel>();

        DateTime hoje = new DateTime();
        

        DB_Amigo db_user = new DB_Amigo();

        public void ListarAmigos()
        {
            DataTable dt_aux = new DataTable();

            dt_aux = db_user.get_Amigo("");

            listaAmigos = dt_aux.AsEnumerable()
                .Select(p => new AmigoModel
                {
                    id = int.Parse(p["id"].ToString()),
                    nome = p["nome"].ToString(),
                    sobrenome = p["sobrenome"].ToString(),
                    aniversario = (DateTime)p["aniversario"]
                }).ToList();

        }

        public void AniversariantesDoDia()
        {
            DataTable dt_aux = new DataTable();

            dt_aux = db_user.lista_Aniversariantes_do_Dia();

            listaAmigosDoDia = dt_aux.AsEnumerable()
                .Select(p => new AmigoModel
                {
                    id = int.Parse(p["id"].ToString()),
                    nome = p["nome"].ToString(),
                    sobrenome = p["sobrenome"].ToString(),
                    aniversario = (DateTime)p["aniversario"]
                }).ToList();

        }

        public void AniversariantesOrdenados()
        {
            hoje = DateTime.Now;
            DataTable dt_aux = new DataTable();

            dt_aux = db_user.lista_Amigos_Ordenados();

            listaAmigosOrdenados = dt_aux.AsEnumerable()
                .Select(p => new AmigoModel
                {
                    id = int.Parse(p["id"].ToString()),
                    nome = p["nome"].ToString(),
                    sobrenome = p["sobrenome"].ToString(),
                    aniversario = (DateTime)p["aniversario"]
                }).ToList();
        }

        public void CriarAmigo(AmigoModel amigoModel)
        {
            db_user.InsertAmigo(amigoModel);
        }

        public void DeletarAmigo(int id)
        {
            db_user.Delete_Amigo(id);
        }

        public void EditarAmigo(AmigoModel amigoModel)
        {
            db_user.Update_Amigo(amigoModel);
        }

        public void BuscarAmigo(string nome)
        {
            DataTable dt_aux = new DataTable();

            db_user.getAmigos(nome);

            buscaAmigo = dt_aux.AsEnumerable()
                .Select(p => new AmigoModel
                {
                    id = int.Parse(p["id"].ToString()),
                    nome = p["nome"].ToString(),
                    sobrenome = p["sobrenome"].ToString(),
                    aniversario = (DateTime)p["aniversario"]
                }).ToList();
        }
    }
}

AT_Pedro-Paiva/Models/AmigoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AT_Pedro_Paiva.Models
{
    public class AmigoModel
    {
        public int id { get; set; }
        [DisplayName("Nome")]
        [Required]
        [StringLength(50, ErrorMessage = "O campo Nome permite no máximo 50 caracteres!")]
        public string nome { get; set; }
        [DisplayName("Sobrenome")]
        [Required]
        public string sobrenome { get; set; }
        [DisplayName("Data de aniversário")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime aniversario { get; set; }

        public IEnumerable<AmigoModel> amigosOrdenados { get; set; }
        public IEnumerable<AmigoModel> amigosDoDia { get; set; }
    }
}

AT_Pedro-Paiva/Controllers/AmigoController.cs
using AT_Pedro_Paiva.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AT_Pedro_Paiva.Controllers
{
    public class AmigoController : Controller
    {
        private Amigo _amigos = new Amigo();

        //Index (lista aniversariantes e lista ordenada crescente aniversariantes)
        public ActionResult Index()
        {
            _amigos.AniversariantesDoDia();
            _amigos.AniversariantesOrdenados();
            _amigos.ListarAmigos();
            var listaGeral = new AmigoModel
            {
                amigosDoDia = _amigos.listaAmigosDoDia,
                amigosOrdenados = _amigos.listaAmigosOrdenados
            };

            return View(listaGeral);
        }

        //Lista Amigo
        public ActionResult ListaAmigo(string busca)
        {
            _amigos.ListarAmigos();
            var listaAmigos = _amigos.listaAmigos;

            if (!String.IsNullOrEmpty(busca))
            {

                listaAmigos = listaAmigos.Where(a => a.nome.ToUpper().Contains(busca.ToUpper())).ToList();
            }
            return View(listaAmigos);
        }


        //Adicionar Amigo
        public ActionResult AdicionarAmigo()
        {
            return View();
        }

        [HttpPost]
        public RedirectToRouteResult AdicionarAmigo(AmigoModel _amigo)
        {
            _amigos.CriarAmigo(_amigo);
            _amigos.ListarAmigos();
            return RedirectToAction("Index");
        }
        
        //Deletar Amigo
        public ActionResult DeletarAmigo(int id)
        {
            _amigos.ListarAmigos();
            return View(_amigos.listaAmigos.Where(p => p.id == id).First());
        }

        [HttpPost]
        public RedirectToRouteResult DeletarAmigo(int id, FormCollection collection)
        {
            _amigos.DeletarAmigo(id);
            _amigos.ListarAmigos();
            return RedirectToAction("Index");
        }

        //Editar Amigo
        public ActionResult EditarAmigo(int id)
        {
            _amigos.ListarAmigos();
            return View(_amigos.listaAmigos.Where(p => p.id == id).First());
        }

        [HttpPost]
        public RedirectToRouteResult EditarAmigo(AmigoModel _amigo)
        {
            _amigos.EditarAmigo(_amigo);
            _amigos.ListarAmigos();
            return RedirectToAction("Index");
        }

        //Detalhar Amigo
        public ActionResult DetalharAmigo(int id)
        {
            _amigos.ListarAmigos();
            return View(_amigos.listaAmigos.Where(p => p.id == id).First());
        }
    }
}

AT_Pedro-Paiva/Views/Amigo/AdicionarAmigo.cshtml
@model AT_Pedro_Paiva.Models.AmigoModel

@{
    ViewBag.Title = "AdicionarAmigo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AdicionarAmigo</h2>
<hr />

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sobrenome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sobrenome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.aniversario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.aniversario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.aniversario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar amigo" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <a href='@Url.Action("Index", "Amigo")' class="btn btn-default btn-md">
        <span class="glyphicon glyphicon-arrow-left"></span> Voltar
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AT_Pedro-Paiva/Views/Amigo/DeletarAmigo.cshtml
@model AT_Pedro_Paiva.Models.AmigoModel

@{
    ViewBag.Title = "DeletarAmigo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Excluir Amigo</h2>

<h3>Você tem certeza que deseja excluir seu amigo?</h3>
<div>
    <h4>AmigoModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sobrenome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sobrenome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aniversario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aniversario)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <a href='@Url.Action("ListaAmigo", "Amigo")' class="btn btn-default btn-md">
                <span class="glyphicon glyphicon-arrow-left"></span> Voltar
            </a>
            <input type="submit" value="Excluir" class="btn btn-danger" />
        </div>
    }
</div>

AT_Pedro-Paiva/Views/Amigo/DetalharAmigo.cshtml
@model AT_Pedro_Paiva.Models.AmigoModel

@{
    ViewBag.Title = "DetalharAmigo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DetalharAmigo</h2>
<hr />

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sobrenome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sobrenome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aniversario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aniversario)
        </dd>

    </dl>
</div>
<p>
    <a href='@Url.Action("ListaAmigo", "Amigo")' class="btn btn-default btn-md">
        <span class="glyphicon glyphicon-arrow-left"></span> Voltar
    </a>
    <a href='@Url.Action("EditarAmigo", "Amigo", new { id = Model.id })' class="btn btn-warning btn-md">
        <span class="glyphicon glyphicon-wrench"></span> Editar
    </a>
</p>

AT_Pedro-Paiva/Views/Amigo/EditarAmigo.cshtml
@model AT_Pedro_Paiva.Models.AmigoModel

@{
    ViewBag.Title = "EditarAmigo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditarAmigo</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sobrenome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sobrenome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.aniversario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.aniversario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.aniversario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    <a href='@Url.Action("ListaAmigo", "Amigo")' class="btn btn-default btn-md">
        <span class="glyphicon glyphicon-arrow-left"></span> Voltar
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AT_Pedro-Paiva/Views/Amigo/Index.cshtml
@model AT_Pedro_Paiva.Models.AmigoModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p></p>

<a href='@Url.Action("AdicionarAmigo", "Amigo")' class="btn btn-primary btn-md">
    <span class="glyphicon glyphicon-plus-sign"></span> Adicionar Amigo
</a>

<h2>Aniversariantes do dia</h2>
<table class="table table-responsive table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.sobrenome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.aniversario)
        </th>
    </tr>

    @foreach (var item in Model.amigosDoDia)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sobrenome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.aniversario)
            </td>
        </tr>

    }
    @if (Model.amigosDoDia.Count().Equals(0))
    {
         <tr><td colspan="3" align="center">Não existem aniversariantes no dia de hoje</td></tr>
    }
</table>

<h2>Aniversariantes mais próximos</h2>
<table class="table table-responsive table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.sobrenome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.aniversario)
        </th>
    </tr>

    @foreach (var item in Model.amigosOrdenados)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sobrenome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.aniversario)
            </td>
        </tr>
    }
</table>

AT_Pedro-Paiva/Views/Amigo/ListaAmigo.cshtml
@model IEnumerable<AT_Pedro_Paiva.Models.AmigoModel>

@{
    ViewBag.Title = "ListaAmigo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Amigos</h2>

<p>
    <a href='@Url.Action("AdicionarAmigo", "Amigo")' class="btn btn-primary btn-md">
        <span class="glyphicon glyphicon-plus-sign"></span> Adicionar Amigo
    </a>

	@using (Html.BeginForm())
    {
	<p>
		<label>Pesquisar amigo: @Html.TextBox("busca", null, new { @class = "form-control" })</label>
        <input type="submit" class="btn btn-info" value="Buscar">
	</p>
	}
</p>

	<table class="table table-responsive table-striped">
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.nome)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.sobrenome)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.aniversario)
			</th>
			<th></th>
		</tr>

		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.nome)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.sobrenome)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.aniversario)
				</td>
				<td>
                    <a href='@Url.Action("EditarAmigo", "Amigo", new { id = item.id })' class="btn btn-warning btn-md">
                        <span class="glyphicon glyphicon-wrench"></span> Editar
                    </a>
                    <a href='@Url.Action("DetalharAmigo", "Amigo", new { id = item.id })' class="btn btn-success btn-md">
                        <span class="glyphicon glyphicon-list-alt"></span> Detalhes
                    </a>
                    <a href='@Url.Action("DeletarAmigo", "Amigo", new { id = item.id })' class="btn btn-danger btn-md">
                        <span class="glyphicon glyphicon-trash"></span> Excluir
                    </a>
				</td>
			</tr>
		}

	</table>

AT_Pedro-Paiva/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AT Pedro Paiva</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        .navbar-inverse{
            background-color: lightseagreen;
        }
        .navbar .navbar-header .navbar-brand, .navbar .navbar-collapse .navv {
            color: white;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Amigos Aniversariantes", "Index", "Amigo", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Amigo", new { @class = "navv"})</li>
                    <li>@Html.ActionLink("Adicionar Amigo", "AdicionarAmigo", "Amigo", new { @class = "navv" })</li>
                    <li>@Html.ActionLink("Todos os amigos", "ListaAmigo", "Amigo", new { @class = "navv" })</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET AT - Pedro Paiva</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>